const $=id=>document.getElementById(id);
let state={data:null};
function fmt(m){m=Math.round(Number(m||0));return `${m<0?"−":""}${Math.floor(Math.abs(m)/60)}h${String(Math.abs(m)%60).padStart(2,"0")}`}
function fmtDate(iso){if(!iso)return"—";return new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Paris"}).format(new Date(iso))}
function dateOnly(iso){return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Paris",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(iso))}
async function api(url,o={}){const r=await fetch(url,{...o,headers:{"Content-Type":"application/json",...(o.headers||{})}}),t=await r.text();let p;try{p=t?JSON.parse(t):{}}catch{throw new Error(`Réponse illisible ${r.status}`)}if(!r.ok)throw new Error(p.error||`Erreur ${r.status}`);return p}
function isoWeekValue(date=new Date()){const d=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate()));d.setUTCDate(d.getUTCDate()+4-(d.getUTCDay()||7));const y=new Date(Date.UTC(d.getUTCFullYear(),0,1));const w=Math.ceil((((d-y)/86400000)+1)/7);return `${d.getUTCFullYear()}-W${String(w).padStart(2,"0")}`}
function mondayFromWeek(value){const [y,w]=value.split("-W").map(Number);const jan4=new Date(Date.UTC(y,0,4));const monday=new Date(jan4);monday.setUTCDate(jan4.getUTCDate()-((jan4.getUTCDay()||7)-1)+(w-1)*7);return monday.toISOString().slice(0,10)}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function duration(row){return Math.max(0,Math.round((new Date(row.ended_at||Date.now())-new Date(row.started_at))/60000))}
function render(){
 const d=state.data,p=d.periods;
 $("statsDate").textContent=new Intl.DateTimeFormat("fr-FR",{dateStyle:"full"}).format(new Date(`${d.today}T12:00:00`));
 $("overtime").textContent=`${d.overtime_minutes>=0?"+":"−"}${fmt(Math.abs(d.overtime_minutes))}`;
 $("paidLeave").textContent=`${d.paid_leave.n1.toFixed(1)} j`;
 $("paidLeaveDetail").textContent=`N−1 : ${d.paid_leave.n1.toFixed(1)} · N : ${d.paid_leave.n.toFixed(1)}`;
 $("todayActivity").textContent=fmt(p.today.actual);$("todayDriving").textContent=`Conduite : ${fmt(p.today.driving)} · ${p.today.km} km`;
 const best=d.consumption[0];$("averageConsumption").textContent=best?`${best.l_per_100km.toFixed(2)} L/100 km`:"—";$("consumptionVehicle").textContent=best?best.vehicle:"Pas assez de pleins";
 $("weekTitle").textContent=`Semaine du ${d.week_start} au ${d.week_end}`;
 $("declarationsList").innerHTML=d.week_declarations.length?d.week_declarations.map(x=>`<div class="list-row"><div><strong>${x.work_date}</strong> · ${fmt(x.total_minutes)}<br><small>${esc(x.notes||"")}</small></div><button data-edit-declaration="${x.work_date}">✎ Modifier</button><button class="delete" data-delete-declaration="${x.id}">🗑</button></div>`).join(""):"<div class=list-row>Aucune heure déclarée.</div>";
 $("weekDeclaredTotal").textContent=`Total de la semaine : ${fmt(d.week_declarations.reduce((s,x)=>s+Number(x.total_minutes),0))}`;
 $("periodCards").innerHTML=[["Aujourd’hui",p.today],["Cette semaine",p.week],["Ce mois",p.month],["Cette année",p.year]].map(([l,x])=>`<article class=period-card><span>${l}</span><strong>${fmt(x.actual)}</strong><small>${fmt(x.expected)} attendues · conduite ${fmt(x.driving)} · ${x.km} km</small></article>`).join("");
 $("consumptionList").innerHTML=table(["Véhicule","Distance","Litres","Consommation"],d.consumption.map(x=>[x.vehicle,`${x.distance} km`,x.litres.toFixed(2),`${x.l_per_100km.toFixed(2)} L/100 km`]));
 $("fuelList").innerHTML=table(["Date","Véhicule","Km","Litres",""],d.fuel_fillups.map(x=>[fmtDate(x.filled_at),x.vehicle_registration,x.odometer_km,Number(x.litres).toFixed(2),actions("fuel",x.id)]));
 renderDaily();
 $("workSessions").innerHTML=table(["Début","Fin","Durée",""],d.work_sessions.map(x=>[fmtDate(x.started_at),fmtDate(x.ended_at),fmt(duration(x)),actions("work",x.id)]));
 $("drivingSessions").innerHTML=table(["Date","Véhicule","Début","Fin","Durée","Km début","Km fin","Distance",""],d.driving_sessions.map(x=>[dateOnly(x.started_at),x.vehicle_registration,fmtDate(x.started_at),fmtDate(x.ended_at),fmt(duration(x)),x.km_start,x.km_end??"—",x.km_end==null?"—":`${x.km_end-x.km_start} km`,actions("driving",x.id)]));
 const dist=d.distance_totals;$("distanceSummary").innerHTML=[["Aujourd’hui",dist.today],["Cette semaine",dist.week],["Ce mois",dist.month],["Cette année",dist.year],["Depuis toujours",dist.all]].map(([l,v])=>`<div><span>${l}</span><strong>${v} km</strong></div>`).join("");
}
function table(headers,rows){return `<table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join("")}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join("")}</tr>`).join(""):`<tr><td colspan="${headers.length}">Aucune donnée.</td></tr>`}</tbody></table>`}
function actions(type,id){return `<div class=record-actions><button data-edit-record="${type}:${id}">✎</button><button class=delete data-delete-record="${type}:${id}">🗑</button></div>`}
function renderDaily(){const period=$("dailyPeriod").value,today=state.data.today;let start;if(period==="week")start=state.data.week_start;else if(period==="month")start=`${today.slice(0,7)}-01`;else start=`${today.slice(0,4)}-01-01`;const rows=state.data.daily.filter(x=>x.date>=start);$("dailyList").innerHTML=table(["Date","Travail réel","Attendu","Conduite","Conduite %","Distance"],rows.map(x=>[x.date,fmt(x.actual_minutes),fmt(x.expected_minutes),fmt(x.driving_minutes),x.actual_minutes?`${(x.driving_minutes/x.actual_minutes*100).toFixed(1)} %`:"0 %",`${x.km} km`]))}
async function load(){state.data=await api(`/api/timeclock/stats?week_start=${mondayFromWeek($("weekPicker").value)}`);render()}
async function openDeclaration(date=state.data.today){const p=await api(`/api/timeclock/declarations?date=${date}`),x=p.declaration||p.prefill||{};$("declareDate").value=date;$("morningStart").value=x.morning_start||"";$("morningEnd").value=x.morning_end||"";$("afternoonStart").value=x.afternoon_start||"";$("afternoonEnd").value=x.afternoon_end||"";$("declareNotes").value=x.notes||"";$("declareDialog").showModal()}
async function submitDeclaration(e){e.preventDefault();await api("/api/timeclock/declarations",{method:"POST",body:JSON.stringify({work_date:$("declareDate").value,morning_start:$("morningStart").value,morning_end:$("morningEnd").value,afternoon_start:$("afternoonStart").value,afternoon_end:$("afternoonEnd").value,notes:$("declareNotes").value})});$("declareDialog").close();await load()}
async function deleteRecord(type,id){if(!confirm("Supprimer cette donnée ?"))return;await api(`/api/timeclock/records/${type}/${id}`,{method:"DELETE"});await load()}
async function editRecord(type,id){const list=type==="work"?state.data.work_sessions:type==="driving"?state.data.driving_sessions:state.data.fuel_fillups,x=list.find(r=>r.id===id);if(!x)return;let body={...x};
 if(type==="work"){body.started_at=prompt("Début ISO",x.started_at)||x.started_at;body.ended_at=prompt("Fin ISO (vide = en cours)",x.ended_at||"")||null}
 if(type==="driving"){body.vehicle_registration=prompt("Véhicule",x.vehicle_registration)||x.vehicle_registration;body.km_start=prompt("Km départ",x.km_start);body.km_end=prompt("Km fin",x.km_end??"");body.started_at=prompt("Début ISO",x.started_at)||x.started_at;body.ended_at=prompt("Fin ISO",x.ended_at||"")||null}
 if(type==="fuel"){body.odometer_km=prompt("Kilométrage",x.odometer_km);body.litres=prompt("Litres",x.litres);body.filled_at=prompt("Date ISO",x.filled_at)||x.filled_at}
 await api(`/api/timeclock/records/${type}/${id}`,{method:"PATCH",body:JSON.stringify(body)});await load()}
$("weekPicker").value=isoWeekValue();$("weekPicker").addEventListener("change",load);$("dailyPeriod").addEventListener("change",renderDaily);$("declareHere").addEventListener("click",()=>openDeclaration());$("declareForm").addEventListener("submit",submitDeclaration);
$("settingsButton").addEventListener("click",()=>{const s=state.data.settings;$("settingOvertime").value=s.overtime_balance_minutes;$("settingOvertimeDate").value=s.overtime_baseline_date;$("settingN1").value=s.paid_leave_n1;$("settingN").value=s.paid_leave_n;$("settingLeaveDate").value=s.paid_leave_baseline_date;$("settingsDialog").showModal()});
$("settingsForm").addEventListener("submit",async e=>{e.preventDefault();await api("/api/timeclock/settings",{method:"POST",body:JSON.stringify({overtime_balance_minutes:$("settingOvertime").value,overtime_baseline_date:$("settingOvertimeDate").value,paid_leave_n1:$("settingN1").value,paid_leave_n:$("settingN").value,paid_leave_baseline_date:$("settingLeaveDate").value})});$("settingsDialog").close();await load()});
document.addEventListener("click",async e=>{const ed=e.target.closest("[data-edit-declaration]"),dd=e.target.closest("[data-delete-declaration]"),dr=e.target.closest("[data-delete-record]"),er=e.target.closest("[data-edit-record]");if(ed)openDeclaration(ed.dataset.editDeclaration);if(dd&&confirm("Supprimer cette déclaration ?")){await api(`/api/timeclock/declarations/${dd.dataset.deleteDeclaration}`,{method:"DELETE"});await load()}if(dr){const [t,id]=dr.dataset.deleteRecord.split(":");deleteRecord(t,id)}if(er){const [t,id]=er.dataset.editRecord.split(":");editRecord(t,id)}});
load().catch(e=>alert(e.message));
